name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dosen:
    path: ../user_group/dosen
  equatable: ^2.0.5
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  mahasiswa:
    path: ../user_group/mahasiswa
  path: ^1.8.2
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
